[package]
name = "crid"
version = "0.1.0"
authors = ["Arpad Borsos <arpad.borsos@googlemail.com>"]

[dependencies]

[dev-dependencies]
quickcheck = "0.6"
criterion = "0.2"

[[bench]]
name = "converter"
harness = false
