[package]
name = "crid-wasm"
version = "0.1.0"
authors = ["Arpad Borsos <arpad.borsos@googlemail.com>"]
publish = false

[lib]
name = "crid_wasm"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
crid = { path = "../crid" }
