[package]
name = "crid-neon"
version = "0.1.0"
publish = false

[lib]
name = "crid_neon"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.23"

[dependencies]
neon = "0.1.23"
crid = { path = "../crid" }
